app:
  info:
    name: ez-admin
    version: 1.0.0
    author: shenyang

server:
  port: 2222
  servlet:
    context-path: /dev-api
spring:
  application:
    name: EZ-ADMIN
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 全局日期格式
    time-zone: Asia/Shanghai          # 时区（按需修改）
    serialization:
      write-dates-as-timestamps: false  # 禁用时间戳格式
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: ${REDIS_HOST}
      # Redis服务器连接端口
      port: ${REDIS_PORT}
      # Redis服务器连接密码（默认为空）
      password: ${REDIS_PASSWORD}
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token前缀
  token-prefix: Bearer
  # token 名称（同时也是 cookie 名称）
  token-name: ${TOKEN_NAME}
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET_KEY}
  # 如果你想交给前端控制，前端拿到 token 自行处理，这里可以设置成false
  is-read-cookie: false
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # 是否输出操作日志
  is-log: true

## mybatis-plus 相关配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  # 打印 sql 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper的扫描，找到所有的mapper.xml映射文件 如果和默认路径一样可以不配置
  mapper-locations: classpath*:/mapper/**/*.xml

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'ezadmin'
      paths-to-match: '/**'
      packages-to-scan: com.ezadmin.api # 扫描接口所在的包
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-version: true # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-host-text: 127.0.0.1:2222
    enable-footer-custom: true
    footer-custom-content: MIT License | Copyright  2024-[ezadmin](https://www.csyblog.cn)
    enable-reload-cache-parameter: true



